// Code generated by MockGen. DO NOT EDIT.
// Source: view/viewer.go
//
// Generated by this command:
//
//	mockgen -source view/viewer.go -destination mocks/view/mock_viewer.go -package view
//

// Package view is a generated GoMock package.
package view

import (
	reflect "reflect"

	globalping "github.com/jsdelivr/globalping-go"
	gomock "go.uber.org/mock/gomock"
)

// MockViewer is a mock of Viewer interface.
type MockViewer struct {
	ctrl     *gomock.Controller
	recorder *MockViewerMockRecorder
}

// MockViewerMockRecorder is the mock recorder for MockViewer.
type MockViewerMockRecorder struct {
	mock *MockViewer
}

// NewMockViewer creates a new mock instance.
func NewMockViewer(ctrl *gomock.Controller) *MockViewer {
	mock := &MockViewer{ctrl: ctrl}
	mock.recorder = &MockViewerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewer) EXPECT() *MockViewerMockRecorder {
	return m.recorder
}

// OutputDefault mocks base method.
func (m *MockViewer) OutputDefault(id string, measurement *globalping.Measurement, opts *globalping.MeasurementCreate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputDefault", id, measurement, opts)
}

// OutputDefault indicates an expected call of OutputDefault.
func (mr *MockViewerMockRecorder) OutputDefault(id, measurement, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputDefault", reflect.TypeOf((*MockViewer)(nil).OutputDefault), id, measurement, opts)
}

// OutputInfinite mocks base method.
func (m *MockViewer) OutputInfinite(measurement *globalping.Measurement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutputInfinite", measurement)
	ret0, _ := ret[0].(error)
	return ret0
}

// OutputInfinite indicates an expected call of OutputInfinite.
func (mr *MockViewerMockRecorder) OutputInfinite(measurement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputInfinite", reflect.TypeOf((*MockViewer)(nil).OutputInfinite), measurement)
}

// OutputJSON mocks base method.
func (m *MockViewer) OutputJSON(id string, measurement []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputJSON", id, measurement)
}

// OutputJSON indicates an expected call of OutputJSON.
func (mr *MockViewerMockRecorder) OutputJSON(id, measurement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputJSON", reflect.TypeOf((*MockViewer)(nil).OutputJSON), id, measurement)
}

// OutputLatency mocks base method.
func (m *MockViewer) OutputLatency(id string, measurement *globalping.Measurement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutputLatency", id, measurement)
	ret0, _ := ret[0].(error)
	return ret0
}

// OutputLatency indicates an expected call of OutputLatency.
func (mr *MockViewerMockRecorder) OutputLatency(id, measurement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputLatency", reflect.TypeOf((*MockViewer)(nil).OutputLatency), id, measurement)
}

// OutputLive mocks base method.
func (m *MockViewer) OutputLive(measurement *globalping.Measurement, opts *globalping.MeasurementCreate, w, h int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputLive", measurement, opts, w, h)
}

// OutputLive indicates an expected call of OutputLive.
func (mr *MockViewerMockRecorder) OutputLive(measurement, opts, w, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputLive", reflect.TypeOf((*MockViewer)(nil).OutputLive), measurement, opts, w, h)
}

// OutputShare mocks base method.
func (m *MockViewer) OutputShare() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputShare")
}

// OutputShare indicates an expected call of OutputShare.
func (mr *MockViewerMockRecorder) OutputShare() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputShare", reflect.TypeOf((*MockViewer)(nil).OutputShare))
}

// OutputSummary mocks base method.
func (m *MockViewer) OutputSummary() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputSummary")
}

// OutputSummary indicates an expected call of OutputSummary.
func (mr *MockViewerMockRecorder) OutputSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputSummary", reflect.TypeOf((*MockViewer)(nil).OutputSummary))
}
