// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jsdelivr/globalping-go (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mocks/globalping/mock_globalping.go -package lib github.com/jsdelivr/globalping-go Client
//

// Package lib is a generated GoMock package.
package lib

import (
	context "context"
	reflect "reflect"

	globalping "github.com/jsdelivr/globalping-go"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AwaitMeasurement mocks base method.
func (m *MockClient) AwaitMeasurement(arg0 context.Context, arg1 string) (*globalping.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AwaitMeasurement", arg0, arg1)
	ret0, _ := ret[0].(*globalping.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AwaitMeasurement indicates an expected call of AwaitMeasurement.
func (mr *MockClientMockRecorder) AwaitMeasurement(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AwaitMeasurement", reflect.TypeOf((*MockClient)(nil).AwaitMeasurement), arg0, arg1)
}

// CacheClean mocks base method.
func (m *MockClient) CacheClean() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CacheClean")
}

// CacheClean indicates an expected call of CacheClean.
func (mr *MockClientMockRecorder) CacheClean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheClean", reflect.TypeOf((*MockClient)(nil).CacheClean))
}

// CachePurge mocks base method.
func (m *MockClient) CachePurge() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CachePurge")
}

// CachePurge indicates an expected call of CachePurge.
func (mr *MockClientMockRecorder) CachePurge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachePurge", reflect.TypeOf((*MockClient)(nil).CachePurge))
}

// CreateMeasurement mocks base method.
func (m *MockClient) CreateMeasurement(arg0 context.Context, arg1 *globalping.MeasurementCreate) (*globalping.MeasurementCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeasurement", arg0, arg1)
	ret0, _ := ret[0].(*globalping.MeasurementCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeasurement indicates an expected call of CreateMeasurement.
func (mr *MockClientMockRecorder) CreateMeasurement(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeasurement", reflect.TypeOf((*MockClient)(nil).CreateMeasurement), arg0, arg1)
}

// GetMeasurement mocks base method.
func (m *MockClient) GetMeasurement(arg0 context.Context, arg1 string) (*globalping.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeasurement", arg0, arg1)
	ret0, _ := ret[0].(*globalping.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeasurement indicates an expected call of GetMeasurement.
func (mr *MockClientMockRecorder) GetMeasurement(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeasurement", reflect.TypeOf((*MockClient)(nil).GetMeasurement), arg0, arg1)
}

// GetMeasurementRaw mocks base method.
func (m *MockClient) GetMeasurementRaw(arg0 context.Context, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeasurementRaw", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeasurementRaw indicates an expected call of GetMeasurementRaw.
func (mr *MockClientMockRecorder) GetMeasurementRaw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeasurementRaw", reflect.TypeOf((*MockClient)(nil).GetMeasurementRaw), arg0, arg1)
}

// Limits mocks base method.
func (m *MockClient) Limits(arg0 context.Context) (*globalping.LimitsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limits", arg0)
	ret0, _ := ret[0].(*globalping.LimitsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Limits indicates an expected call of Limits.
func (mr *MockClientMockRecorder) Limits(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limits", reflect.TypeOf((*MockClient)(nil).Limits), arg0)
}

// Probes mocks base method.
func (m *MockClient) Probes(arg0 context.Context) (*globalping.ProbesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probes", arg0)
	ret0, _ := ret[0].(*globalping.ProbesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Probes indicates an expected call of Probes.
func (mr *MockClientMockRecorder) Probes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probes", reflect.TypeOf((*MockClient)(nil).Probes), arg0)
}

// SetToken mocks base method.
func (m *MockClient) SetToken(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToken", arg0)
}

// SetToken indicates an expected call of SetToken.
func (mr *MockClientMockRecorder) SetToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockClient)(nil).SetToken), arg0)
}
