// Code generated by MockGen. DO NOT EDIT.
// Source: api/client.go
//
// Generated by this command:
//
//	mockgen -source api/client.go -destination mocks/api/mock_client.go -package api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	api "github.com/jsdelivr/globalping-cli/api"
	globalping "github.com/jsdelivr/globalping-go"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockClient) Authorize(ctx context.Context, callback func(error)) (*api.AuthorizeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, callback)
	ret0, _ := ret[0].(*api.AuthorizeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockClientMockRecorder) Authorize(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockClient)(nil).Authorize), ctx, callback)
}

// AwaitMeasurement mocks base method.
func (m *MockClient) AwaitMeasurement(ctx context.Context, id string) (*globalping.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AwaitMeasurement", ctx, id)
	ret0, _ := ret[0].(*globalping.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AwaitMeasurement indicates an expected call of AwaitMeasurement.
func (mr *MockClientMockRecorder) AwaitMeasurement(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AwaitMeasurement", reflect.TypeOf((*MockClient)(nil).AwaitMeasurement), ctx, id)
}

// Close mocks base method.
func (m *MockClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// CreateMeasurement mocks base method.
func (m *MockClient) CreateMeasurement(ctx context.Context, measurement *globalping.MeasurementCreate) (*globalping.MeasurementCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeasurement", ctx, measurement)
	ret0, _ := ret[0].(*globalping.MeasurementCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeasurement indicates an expected call of CreateMeasurement.
func (mr *MockClientMockRecorder) CreateMeasurement(ctx, measurement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeasurement", reflect.TypeOf((*MockClient)(nil).CreateMeasurement), ctx, measurement)
}

// GetMeasurement mocks base method.
func (m *MockClient) GetMeasurement(ctx context.Context, id string) (*globalping.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeasurement", ctx, id)
	ret0, _ := ret[0].(*globalping.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeasurement indicates an expected call of GetMeasurement.
func (mr *MockClientMockRecorder) GetMeasurement(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeasurement", reflect.TypeOf((*MockClient)(nil).GetMeasurement), ctx, id)
}

// GetMeasurementRaw mocks base method.
func (m *MockClient) GetMeasurementRaw(ctx context.Context, id string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeasurementRaw", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeasurementRaw indicates an expected call of GetMeasurementRaw.
func (mr *MockClientMockRecorder) GetMeasurementRaw(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeasurementRaw", reflect.TypeOf((*MockClient)(nil).GetMeasurementRaw), ctx, id)
}

// Limits mocks base method.
func (m *MockClient) Limits(ctx context.Context) (*globalping.LimitsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limits", ctx)
	ret0, _ := ret[0].(*globalping.LimitsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Limits indicates an expected call of Limits.
func (mr *MockClientMockRecorder) Limits(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limits", reflect.TypeOf((*MockClient)(nil).Limits), ctx)
}

// Logout mocks base method.
func (m *MockClient) Logout(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockClientMockRecorder) Logout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockClient)(nil).Logout), ctx)
}

// RevokeToken mocks base method.
func (m *MockClient) RevokeToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockClientMockRecorder) RevokeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockClient)(nil).RevokeToken), ctx, token)
}

// TokenIntrospection mocks base method.
func (m *MockClient) TokenIntrospection(ctx context.Context, token string) (*api.IntrospectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenIntrospection", ctx, token)
	ret0, _ := ret[0].(*api.IntrospectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenIntrospection indicates an expected call of TokenIntrospection.
func (mr *MockClientMockRecorder) TokenIntrospection(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenIntrospection", reflect.TypeOf((*MockClient)(nil).TokenIntrospection), ctx, token)
}
